### ISSUE TITLE
Enable messages to be transferred with multiple frames via a specialized Writer

### ISSUE THREAD

**Issue by Luka967** [Luka967/CSSockets#4]
A call such as `WebSocket.PipedMessage(bool isString)` would return a `Writer`-inherited class to which one can pipe data to. To ensure the message gets terminated, all streams will need to have a new `OnEnd` event.

**Comment by Fan7asy** [comment]
A call such as `WebSocket.PipedMessage(bool isString)` would return a `Writer`-inherited class to which one can pipe data to. To ensure the message gets terminated, all streams will need to have a new `OnEnd` event.

**Comment by Luka967** [comment]
Done, but only for binary messages, and it should suffice.
